name: BetaDeaths
version: '1.1'
main: me.lukiiy.BetaDeaths.BetaDeaths
author: Lukiiy
description: Adds Death Messages to old beta versions
softdepend: [DiscordBridge]
commands:
  betadeaths:
    description: Reloads the plugin
    permission: betadeaths.reload