name: BetaDeaths
version: '${project.version}'
main: me.lukiiy.BetaDeaths.BetaDeaths
author: Lukiiy
description: Adds Death Messages to old beta versions
commands:
  betadeaths:
    description: Reloads the plugin
    permission: betadeaths.reload